services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: db_poo
      SECRET_KEY: 'cambiatuclaveaqui'

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro

volumes:
  mysql_data: